### PR TITLE
Created src directory and split up code

### PR DESCRIPTION
**Pull request by sympmarc**
Added package.json and gulpfile

### CODE REVIEW

**Comment by johnnliu** [comment]
gulp build does TODO!

**Comment by sympmarc** [comment]
I didn't want to make it TOO easy for you. ;+)

**Comment by sympmarc** [comment]
Now you have separate files that you can build from. Wasn't sure how you wanted to go at that given the changes you've been making.

**Comment by johnnliu** [comment]
I have been going from the 3 separate files since the split.  It works nice.  I had to move "strict" inside the function rather than the first line inside the script tag.

**Pull request merged**
